### PR TITLE
Draft: adding initial docs repo

### PR DESCRIPTION
**Pull request by LAShemilt**
adding a docs file and Github pages workflow to SciCat live to form a documentation that sits next to the repository.
Docs will be published through Github workflows when main is updated. 

This will be referenced in the SciCat official website as the "Getting Started" guide. See the companion PR here: https://github.com/SciCatProject/scicatproject.github.io/pull/50

### CODE REVIEW

**Comment by minottic** [comment]
can the "SciCat official website" simply link the README? or is the HTML page required?

**Comment by minottic** [comment]
or maybe, could the html be auto generated from the .mds?

**Comment by LAShemilt** [comment]
The idea that the "official" scicat webpage would link out to a set of autogenerated docs on a https://github.io page. 
So each repo in the project would have it's own docs site, that could be linked to from a simple readme.

**Comment by LAShemilt** [comment]
> or maybe, could the html be auto generated from the .mds?

yes that is the plan, to use the github workflow to auto generate html from readmes.

**Comment by minottic** [comment]
closed by #217 . @LAShemilt I have added the CI for mkdocs as a start, happy to review it after the documentation decision is more mature.

Thanks!

**Pull request closed without merging**
