### PR TITLE
Amend datasets to fix fe issues

### PR DESCRIPTION
**Pull request by minottic**
Keys used in datasets did not comply with the ones expected by catanie. This PR should fix this issue

### CODE REVIEW

**Comment by nitrosx** [comment]
Looks good to me.

**Comment by minottic** [comment]
@nitrosx do you still experience issues with datasets in catanie?

**Comment by stephan271** [comment]
There are still some errors, e.g. raw data do not have input data sets or software linked and derived data I think are not linked to the same objecsts than raw data

**Comment by minottic** [comment]
@stephan271 ok, I will fix. What do you mean by this: `derived data I think are not linked to the same objecsts than raw data`? If you mean that not all derived have input datasests, yes, that is because for some derived datasets I have the software used but not the input datasets

**Comment by nitrosx** [comment]
@minottic: I will let you know by tomorrow morning

**Comment by stephan271** [comment]
> @stephan271 ok, I will fix. What do you mean with this: `derived data I think are not linked to the same objecsts than raw data`? If you mean that not all derived have input datasests, yes, that is because for some derived datasets I have the software used but not the input datasets

No, what I mean is that the relations to sample, proposal, instruments etc only exist for raw data.

**Comment by minottic** [comment]
@stephan271 , ok I will remove those as well. I wish I found this page earlier: https://scicatproject.github.io/documentation/Ingestor/ingestManual.html#sec-8-6-1

**Comment by minottic** [comment]
@stephan271, I was having a look at catanie and for derived datasets sample and proposal are rendered. E.g.: https://scicat.ess.eu/anonymous/datasets/20.500.12269%2FBRIGHTNESS%2FNMX0044.

Shall I get rid of it anyway to be compliant with the collection definition in catamel?

**Comment by stephan271** [comment]
I would say yes, stay compliant with catamel. The displayed proposal may in fact come from the linked raw dataset ?

**Comment by minottic** [comment]
@stephan271 , no I think they come from the derived dataset directly. ANyway, I removed those relations

**Comment by nitrosx** [comment]
Carlo
I just checked the latest version and the dataset page is fully populated with a set of datasets. Also I checked the console and I do not see the error that was there before.
Thanks

**Comment by minottic** [comment]
Thanks @nitrosx . 

I will merge then

**Pull request merged**
