### PR TITLE
Use the new backend in scicatlive

### PR DESCRIPTION
**Pull request by linupi**
I tried to have a look what is needed to use the new backend in scicatlive. To simplify life I disabled the seed_db for the beginning since it requires some changes for the migration to work.

Putting in place the configuration in the new format I was able to have a running backend-next container. At first glance also the login through the frontend seems to work but any interaction with the frontend (e.g. displaying proposal or sample list) causes an automatic logout of the user.

The fist obvious question would be if I´d have to use an adopted version of the frontend. Also is `ghcr.io/scicatproject/backend-next:latest` the right source of the backend image that we would want to use in SciCat live?

Open TODOs:
- [x] fix frontend issues described above
- [x] migrate seed_db to new backend
- [ ] deal with ldap config ??

### CODE REVIEW

**Comment by linupi** [comment]
I think I could track down Auth problem that I am having in the frontend a bit. Here is a screenshot of the first failing request when trying to display the proposal list after having loged in:

grafik

Please note the "undefined" in the beginning of the _Authorization_ header. Trying to do the same thing in _Postman_ actually helped me to first reproduce the issue:

grafik

and also solve it by replacing `undefined` by `Bearer `.

grafik

The question now would be what I'd have to do in terms of configuration of the frontend to have `Bearer ` instead of  `undefined`

**Comment by linupi** [comment]
any ideas who would be the person to ask for help / tips  with this @nitrosx ?

**Comment by nitrosx** [comment]
@linupi: I guess that at the moment @minottic  or mysel would be the ones to talk to.
The only issue is that I'm working on getting up to speed with the frontend after Henrik has left.
Give me until tuesday, I see if I can get an answer for you.

Regarding the frontend, I would say that you should test against the last release. If we test against the latest version, you might get some new features that introduce or modify the behavior of the frontend.

**Comment by minottic** [comment]
hi @linupi , if I remember correctly, it should be enough to set [this variable](https://github.com/SciCatProject/scicatlive/blob/master/config/frontend/config.json#L2) to "Bearer " (I guess with the trailing space, but I am not too sure)

**Comment by linupi** [comment]
thank you @minottic! the  "Bearer " in front of _accessTokenPrefix_ does the job.

**Comment by linupi** [comment]
@nitrosx @minottic : I migrated the seed_db and fixed the frontend login issue the way Carlo suggested. Remains only the LDAP to look into, but that is not really on my agenda.

I am not sure if we want to merge the new backend dependency directly in the master of scicatlive, but since I can not create branches here I'd delegate that to one of you after review...

**Comment by minottic** [comment]
hi @linupi, thanks! Changes look cool, I think that since the new backend is still buggy and under test. I'll also add you to the repo as a developer and we can create a new branch. About LDAP, why is this related to this PR? Could it be addressed in another PR or is it needed by the new be?

**Comment by linupi** [comment]
the content of this merge request is now available in the [`with-backen-next` branch](https://github.com/SciCatProject/scicatlive/tree/with-backend-next)

**Pull request closed without merging**
