### PR TITLE
Remove seed container

### PR DESCRIPTION
**Pull request by fpotier**
Linked to #53

- Use official mongo image rather than the bitnami one
- Upgrade to mongo 7.0 as 4.2 is no longer supported
- Replace seed container by an init script

### CODE REVIEW

**Review by minottic — COMMENTED** [review]
can we keep the `json` files? I think it will be easier if anyone wants to add a new collection seed to just add the json file rather than changing the .js script

**Comment by fpotier** [comment]
Why do we need 2 database?

**Comment by minottic** [comment]
because the new be and the old one rely on slightly different schemas and I think it would be a little counterintuitive to have both be writing on the same one. But for now I think one is fine, it's probably a change for later

**Comment by minottic** [comment]
closed by: #56

**Pull request closed without merging**
