### PR TITLE
Add config field for fe4.6 compatibility

### PR DESCRIPTION
**Pull request by minottic**

### CODE REVIEW

**Comment by minottic** [comment]
depends on #374

**Comment by sbliven** [comment]
Which commit did you take the config file from?

Would it be possible not to duplicate `config.js` between scicatlive and frontend? Or else use a very minimal config, where any unchanged values are omitted? Right now we frequently have big changes between config.js between frontend branches, making it hard to migrate the scicatlive configuration without causing merge conflicts. My current dev workflow is (1) build containers (2) stash changes, which are usually just config.js (3) check out the new branch, (4) stash pop.

**Comment by sbliven** [comment]
Ahh, seems to be from the current master (last changed in [9f90abd](https://github.com/SciCatProject/frontend/blob/9f90abd781bd8c991e10e56f1148c9865e58ceb0/cypress/support/commands.js))

**Review by sbliven — APPROVED** [review]
I'm approving this since we need constancy with the frontend, but it would be nice to have a long-term solution.

**Comment by minottic** [comment]
relates to #377

**Pull request merged**
