### PR TITLE
https / letsencrypt config

### LINKED ISSUE #58: Https via Letsencrypt
Traefik allows for automatic issuance of TLS certificates from letsencrypt via a few configuration options.
Https should not be optional even in a test setup.

### PR DESCRIPTION
**Pull request by belfhi**
fixes #58

### CODE REVIEW

**Comment by minottic** [comment]
thanks, I am not 100% sure I see the usecase for tls in a local setup, but it won't hurt, so I think it's a nice addition! 

Do you know what happens when the certificate expires?

**Comment by belfhi** [comment]
I didn't really have a _localhost_ setup in mind, rather a virtual machine with a public IP / Hostname.
In that case this docker-compose setup can even be used in a more serious manner than "just" development when the complexity of e.g. Kubernetes is too much :)

**Comment by belfhi** [comment]
yes, that's the URL I was talking about.  When you're confident that the server is reachable from the outside (letsencrypt needs access to port 80) you can use `"--certificatesResolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory`.

Letsencrypt has a [rate limit(https://letsencrypt.org/docs/rate-limits/)  _per domain_, so it only affects you locally.

**Comment by minottic** [comment]
ok, then this opens another question I had... letsencrypt does a callback to the host which is asking for a certificate if I remember well, so this means that this will only work if scicatlive is reachable on a public URL. 

This also means that no TLS termination happens if I just use scicatlive in my laptop without exposing the URL, right?

**Comment by belfhi** [comment]
right, this config is meant for a test setup on a host with a public IP (and DNS for that matter). For a local setup with TLS self-signed certs would have to be used.

**Comment by minottic** [comment]
ok, but then this PR does a change for a very specific use case which often will not be used. 

1. should the TLS happen at your facility rather than enforced by this traefik
2. if not, I would need to think a little. I am not entirely convinced this will be beneficial in the general usecase, thus if it should be on master. Basically because most of the times this will not be used and we might risk to create expectations

**Comment by minottic** [comment]
sorry for the wait. We have made quite some changes recently and after that, I think this could indeed live well here, if we somehow manage the below:

1. traefik container: I would make sure that all the traefik additional options are required, as otherwise, it will add unrequired complexity
2. traefik container:  same for the additional volume mounting (which I am unsure I understand)
3. traefik labels in different containers: I would try to see if one can avoid adding these new labels and somehow make the services use them by default (maybe by setting the traefik container defaults(?)). Otherwise, the more labels we have, the harder it becomes to add a new service in the future
4. I would make sure that this doesn't break the current local deployment
5. it should follow the new services structure
6. we should add a README in the `proxy` service which explains when and how to use this

1 and 2 are somehow optional, while the rest I think it's fairly important

again thanks a lot for the proposition and sorry for the git conflicts!

**Comment by LAShemilt** [comment]
I agree that we probably don't need letsencrypt in a local version. However, it is useful to add a README that explains how to use this if people want to set up certificates. 

We could argue that addition of certs is outside the remit of scicatlive as this is something that a developer may already know how to do .

**Comment by minottic** [comment]
@belfhi would you be willing to make these changes? If so, your proposed change will be included in scicatlive

**Pull request closed without merging**
